server:
  port: 8188
  servlet:
    context-path: /botanica/api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_botanica?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
  flyway:
    baseline-on-migrate: true
jwt:
  secret: IIBIukkn887*&^&%&%CVJhghhkhkkgyg6546%%^5787z
  lifetime: 36000000

integrations:
  user-service:
    url: http://localhost:8187/botanica/api
    connection-timeout: 10000
    read-timeout: 1000
    write-timeout: 1000

